ankyrins_home:
    pattern:  /
    defaults: { _controller: LFPStructuralAnksMainBundle:Home:index }
    
ankyrins_browse:
    pattern:  /browse
    defaults: { _controller: LFPStructuralAnksMainBundle:Home:browse }