ankyrins_home:
    pattern:  /
    defaults: { _controller: LFPStructuralAnksMainBundle:Home:index }
    
ankyrins_browse:
    pattern:  /browse
    defaults: { _controller: LFPStructuralAnksMainBundle:Home:browse }
    
ankyrins_show:
    pattern:  /show/{pdbId}/{chainId}
    defaults: { _controller: LFPStructuralAnksMainBundle:Home:show }    