parameters:
#    lfp_structural_anks_main.example.class: LFP\StructuralAnks\MainBundle\Example

services:
#    lfp_structural_anks_main.example:
#        class: %lfp_structural_anks_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    main.twig.get_contents_extension:
        class: LFP\StructuralAnks\MainBundle\Twig\GetContentsExtension
        tags:
            - { name: twig.extension }
    main.twig.all_purpose_extension:
        class: LFP\StructuralAnks\MainBundle\Twig\AllPurposeExtension
        tags:
            - { name: twig.extension }